In [2]:
# 这是你的第一个单元格
print("Hello, Deep Learning!")
import torch
print(f"PyTorch版本: {torch.__version__}")

Hello, Deep Learning!
PyTorch版本: 2.5.1


In [22]:
import torch
x = torch.arange(12)  #张量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
x.shape    #张量的形状

torch.Size([12])

In [21]:
x.numel()  #张量中元素的总数 

12

In [26]:
x = x.reshape(3, 4)  #改变张量的形状，不改变张量的元素值和元素总数
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [34]:
torch.zeros(2, 3, 4)  # 全零张量，与 torch.zeros((2, 3, 4))一样

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [28]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [29]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [30]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [31]:
y = (3, 4, 5)
y

(3, 4, 5)

In [32]:
torch.ones(y)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [39]:
z = torch.tensor([[[7, 3, 2, 1], [4, 8, 0, 3]], [[1, 1, 1, 1], [2, 2, 2, 2]]]) # 为张量tensor中的每个元素赋予确定值
z

tensor([[[7, 3, 2, 1],
         [4, 8, 0, 3]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2]]])

In [40]:
z.shape

torch.Size([2, 2, 4])

In [41]:
z.numel()

16

In [42]:
z.reshape(2, 8)

tensor([[7, 3, 2, 1, 4, 8, 0, 3],
        [1, 1, 1, 1, 2, 2, 2, 2]])

In [49]:
z.reshape(2, 4, 2)

tensor([[[7, 3],
         [2, 1],
         [4, 8],
         [0, 3]],

        [[1, 1],
         [1, 1],
         [2, 2],
         [2, 2]]])

In [48]:
# 常见的 + - * / 和 ** 都可以按元素运算，** 运算符是求幂运算符
x = torch.tensor([[1.0, 1, 1], [2, 3, 5]])   # 用 1.0，代表此张量所有元素为浮点数，不然为整数
y = torch.tensor([[1, 2, 2], [1, 1, 2]])
x + y,x - y,x * y,x / y,x ** y

(tensor([[2., 3., 3.],
         [3., 4., 7.]]),
 tensor([[ 0., -1., -1.],
         [ 1.,  2.,  3.]]),
 tensor([[ 1.,  2.,  2.],
         [ 2.,  3., 10.]]),
 tensor([[1.0000, 0.5000, 0.5000],
         [2.0000, 3.0000, 2.5000]]),
 tensor([[ 1.,  1.,  1.],
         [ 2.,  3., 25.]]))

In [55]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[1.0, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]])
x,y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.]]))

In [61]:
# 把多个张量连结在一起，若张量是2维的，dim=0 代表按行连结
torch.cat((x, y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.]])

In [60]:
# 把多个张量连结在一起，若张量是2维的，dim=1 代表按列连结
torch.cat((x, y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  1.,  1.],
        [ 4.,  5.,  6.,  7.,  2.,  2.,  2.,  2.],
        [ 8.,  9., 10., 11.,  3.,  3.,  3.,  3.]])

In [68]:
# 把多个张量连结在一起，若张量是3维的，dim=0 代表按第一维连结
x = torch.arange(12)
x = x.reshape(2, 2, 3)
y = torch.ones(2, 2, 3)
z = torch.zeros(2, 2, 3)
torch.cat((x, y, z), dim=0)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]])

In [72]:
# 把多个张量连结在一起，若张量是3维的，dim=1 代表按第二维连结（按行）
x = torch.arange(12)
x = x.reshape(2, 2, 3)
y = torch.ones(2, 2, 3)
z = torch.zeros(2, 2, 3)
torch.cat((x, y, z), dim=1)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.]]])

In [73]:
# 把多个张量连结在一起，若张量是3维的，dim=2 代表按第三维连结（按列）
x = torch.arange(12)
x = x.reshape(2, 2, 3)
y = torch.ones(2, 2, 3)
torch.cat((x, y), dim=2)

tensor([[[ 0.,  1.,  2.,  1.,  1.,  1.],
         [ 3.,  4.,  5.,  1.,  1.,  1.]],

        [[ 6.,  7.,  8.,  1.,  1.,  1.],
         [ 9., 10., 11.,  1.,  1.,  1.]]])

In [74]:
x == y

tensor([[[False,  True, False],
         [False, False, False]],

        [[False, False, False],
         [False, False, False]]])

In [80]:
# 对张量中所有元素求和，会得到只有一个元素的张量
z = y.sum()
z

tensor(12.)

In [85]:
# 即使形状不同，仍可以通过调用广播机制来执行按元素操作。所以当结果不对时，需要考虑是否是广播机制导致的，检查代码是否正确
A = torch.arange(3).reshape(3,1)
B = torch.arange(2).reshape(1,2)
A,B,A + B


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [87]:
# 可以用[-1]选择最后一个元素，用[1:3]选择第二个和第三个元素
A[-1],A[1:3]

(tensor([2]),
 tensor([[1],
         [2]]))

In [89]:
# 可以通过指定索引，将元素值写入张量
a = torch.ones(3,2,3)
a[0, 1, 1] = 88
a

tensor([[[ 1.,  1.,  1.],
         [ 1., 88.,  1.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]])

In [94]:
# 为多个元素赋值相同的值，只需索引所有元素，然后为他们赋值
a = torch.ones(3, 4, 3)
a[0:2, 1:3, 0:2] = 99
a

tensor([[[ 1.,  1.,  1.],
         [99., 99.,  1.],
         [99., 99.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [99., 99.,  1.],
         [99., 99.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]])

In [107]:
# 下述操作会为新结果分配新内存
A = torch.arange(3).reshape(3,1)
B = torch.ones(3,1)
before_id = id(A)
print('before_id(A):',id(A))
A = A + B
now_id = id(A)
print('now_id(A):',id(A))
print('is_equal:', before_id == now_id)

before_id(A): 1802671043984
now_id(A): 1802671221632
is_equal: False


In [108]:
# 下述操作不会为Z分配新内存，在原地操作
Z = torch.zeros_like(A)
before_id = id(Z)
print('before_id(Z):', id(Z))
Z[:] = A + B
now_id = id(Z)
print('now_id(Z):', id(Z))
print('is_equal:', before_id == now_id)

before_id(Z): 1802671042944
now_id(Z): 1802671042944
is_equal: True


In [109]:
# 如果在后续计算中没有重复使用 A,可以用下述两种原地操作，减少操作的内存开销
id_1 = id(A)
A += B
id_2 = id(A)
print('is_equal', id_1 == id_2)
A[:] = A + B
id_3 = id(A)
print('is_equal', id_2 == id_3)

is_equal True
is_equal True


In [116]:
# 转换为 NumPy 张量
a = A.numpy()
type(a),type(A)

(numpy.ndarray, torch.Tensor)

In [119]:
# 将大小为1的张量转换为python标量
a = torch.tensor([3.5])
print('a=', a)
print('标量a：', a.item())
print('标量a：', float(a))
print('标量a：', int(a))

a= tensor([3.5000])
标量a： 3.5
标量a： 3.5
标量a： 3
