In [1]:
# 标量由只有一个元素的张量表示
import torch
x = torch.tensor([4.0])
y = torch.tensor([2.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)

tensor([6.])
tensor([2.])
tensor([8.])
tensor([2.])
tensor([16.])


In [1]:
# 注意区分张量中：只有一个元素的一维向量、一个标量
import torch
a = torch.tensor([2.3])
print('==============一维向量a===========\n')
print(a.shape)
print(a.dim())
print(a)

b = torch.tensor([1.2, 4.5, 9])
print('==============一维向量b===========\n')
print(b.shape)
print(b)
print(b.dim())

c = torch.randn(size=())
print('=============随机标量c============\n')
print(c.shape)
print(c)
print(c.dim())
print(c.item())

d = torch.tensor(8.8)
print('============标量d================\n')
print(d.shape)  # 形状
print(d.dim())  # 维度总数
print(d.item()) # 获取python标量值

==============一维向量a===========

torch.Size([1])
1
tensor([2.3000])
==============一维向量b===========

torch.Size([3])
tensor([1.2000, 4.5000, 9.0000])
1
=============随机标量c============

torch.Size([])
tensor(0.1961)
0
0.1960923820734024
============标量d================

torch.Size([])
0
8.800000190734863


In [3]:
# 将向量视为标量值组成的列表
x = torch.arange(5)
x

tensor([0, 1, 2, 3, 4])

In [4]:
# 通过张量的索引来访问任一元素
a = x[2]
a

tensor(2)

In [5]:
print('张量长度\n',len(x))
print('张量形状\n', x.shape)

张量长度
 5
张量形状
 torch.Size([5])


In [6]:
# 通过指定两个分量m和n来创建一个形状为m*n的矩阵
A = torch.ones(4,5)
B = torch.arange(12).reshape(3,4)
A, B

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [9]:
# 矩阵的转置
A_T = A.T
print(A_T)
print(B.T)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


In [12]:
# 可以构建更多轴的数据结构
A = torch.ones(2, 3, 4)
B = torch.arange(24).reshape(2, 3, 4)
A, B

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]))

In [16]:
# 相同形状的任何两个张量，按元素二元运算的结果都将是相同形状的张量
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [29]:
# 两个矩阵按元素相乘：哈达玛积
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
print('方法1：\n', A * B)
print('方法2：\n', torch.mul(A, B))
print('方法3：\n', torch.multiply(A, B))

方法1：
 tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])
方法2：
 tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])
方法3：
 tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


In [30]:
# 一个标量与一个矩阵相加，一个标量与一个矩阵相乘
x = 2
A_ = torch.ones(2, 3, 4)
print('一个标量与一个矩阵相加\n', x + A_)
print('一个标量与一个矩阵相乘\n', x * A_)
(x * A_).shape

一个标量与一个矩阵相加
 tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]])
一个标量与一个矩阵相乘
 tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])


torch.Size([2, 3, 4])

In [33]:
# 计算张量元素的和，和是一个标量
x = torch.arange(4, dtype=torch.float32).reshape(2,2)
x.sum()

tensor(6.)

In [38]:
# 指定一个轴求和，结果是剩下轴的形状
A = torch.arange(24).reshape(3, 4, 2)
print('A\n', A)
print('按第一个轴求和\n', A.sum(axis=0))
print('按第二个轴求和\n', A.sum(axis=1))
print('按第三个轴求和\n', A.sum(axis=2))

A
 tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]])
按第一个轴求和
 tensor([[24, 27],
        [30, 33],
        [36, 39],
        [42, 45]])
按第二个轴求和
 tensor([[12, 16],
        [44, 48],
        [76, 80]])
按第三个轴求和
 tensor([[ 1,  5,  9, 13],
        [17, 21, 25, 29],
        [33, 37, 41, 45]])


In [41]:
# 指定两个轴求和，结果是剩下轴的形状
A = torch.arange(24, dtype=torch.float32).reshape(3, 4, 2)
print('按第一个轴和第二个轴求和\n', A.sum(axis=[0, 1]))
print('按第一个轴和第三个轴求和\n', A.sum(axis=[0, 2]))
print('按第二个轴和第三个轴求和\n', A.sum(axis=[1, 2]))

按第一个轴和第二个轴求和
 tensor([132., 144.])
按第一个轴和第三个轴求和
 tensor([51., 63., 75., 87.])
按第二个轴和第三个轴求和
 tensor([ 28.,  92., 156.])


In [61]:
# 求平均值
A = torch.arange(4, dtype=torch.float32).reshape(2, 2)
print('方法1：\n', A.mean())
print('方法2：\n', A.sum() / A.numel())

方法1：
 tensor(1.5000)
方法2：
 tensor(1.5000)


In [62]:
# 按特定轴求平均值
A.mean(axis=0)

tensor([1., 2.])

In [63]:
# 计算总和或均值时保持轴数不变
A = torch.arange(24, dtype=torch.float32).reshape(3, 2, 4)
sum_A = A.sum(axis=1, keepdims=True)
sum_A_temp = A.sum(axis=1)
print('计算总和时保持轴数不变：\n', sum_A)
print('计算总和时轴数改变：\n', sum_A_temp)
print('计算均值时保持轴数不变：\n', A.mean(axis=1, keepdims=True))
print('计算均值时轴数改变：\n', A.mean(axis=1))

计算总和时保持轴数不变：
 tensor([[[ 4.,  6.,  8., 10.]],

        [[20., 22., 24., 26.]],

        [[36., 38., 40., 42.]]])
计算总和时轴数改变：
 tensor([[ 4.,  6.,  8., 10.],
        [20., 22., 24., 26.],
        [36., 38., 40., 42.]])
计算均值时保持轴数不变：
 tensor([[[ 2.,  3.,  4.,  5.]],

        [[10., 11., 12., 13.]],

        [[18., 19., 20., 21.]]])
计算均值时轴数改变：
 tensor([[ 2.,  3.,  4.,  5.],
        [10., 11., 12., 13.],
        [18., 19., 20., 21.]])


In [65]:
# 按特定轴累加求和
B = torch.arange(12, dtype=torch.float32).reshape(3, 4)
print(B)
print('按第一个轴累积求和\n', B.cumsum(axis=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
按第一个轴累积求和
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.]])


In [68]:
# 两个一维张量是两个向量，计算这两个向量的点积
a = torch.arange(4, dtype=torch.float32)
b = torch.ones(4, dtype=torch.float32)
c = torch.tensor([2.0, 5, 1, 3])
print(a, b, c)
print('向量a和向量b的点积\n', torch.dot(a, b))

tensor([0., 1., 2., 3.]) tensor([1., 1., 1., 1.]) tensor([2., 5., 1., 3.])
向量a和向量b的点积
 tensor(6.)


In [69]:
# 矩阵与向量相乘
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
x = torch.arange(4, dtype=torch.float32)
print(A.shape, x.shape)
print(A, x)
print('矩阵A与向量x相乘\n', torch.mv(A, x))

torch.Size([3, 4]) torch.Size([4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) tensor([0., 1., 2., 3.])
矩阵A与向量x相乘
 tensor([14., 38., 62.])


In [73]:
# 矩阵与矩阵相乘
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
B = torch.arange(20, dtype=torch.float32).reshape(4, 5)
print('矩阵A和矩阵B相乘\n', torch.mm(A, B))

矩阵A和矩阵B相乘
 tensor([[ 70.,  76.,  82.,  88.,  94.],
        [190., 212., 234., 256., 278.],
        [310., 348., 386., 424., 462.]])


In [2]:
# 矩阵的各种运算
A = torch.ones(2, 3)
B = torch.tensor([[1.0, 5, 2], [4, 2, 8]])
C = torch.ones(3, 2)
print('A=\n', A)
print('B=\n', B)
print('C=\n', C)

# 基本运算
print("加法:\n", A + B)
print("减法:\n", A - B)
print("逐元素乘法:\n", A * B)  # 或 torch.mul(A, B)
print("逐元素除法:\n", A / B)  # 或 torch.div(A, B)
print("矩阵乘法:\n", A @ C)    # 或 torch.matmul(A, C)

# 转置
print("A 的转置:", A.T)  # 或 A.t(), torch.transpose(A, 0, 1)

# 重塑
print("重塑为向量:", A.flatten())  # 或 A.reshape(-1)
print("重塑形状:", A.reshape(1, 6))

# 改变维度
D = torch.arange(12).reshape(3, 4)
print("原始形状:", D.shape)
print("增加维度:", D.unsqueeze(0).shape)  # [1, 3, 4]
print("减少维度:", D.squeeze().shape)     # 移除所有大小为1的维度

A=
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
B=
 tensor([[1., 5., 2.],
        [4., 2., 8.]])
C=
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
加法:
 tensor([[2., 6., 3.],
        [5., 3., 9.]])
减法:
 tensor([[ 0., -4., -1.],
        [-3., -1., -7.]])
逐元素乘法:
 tensor([[1., 5., 2.],
        [4., 2., 8.]])
逐元素除法:
 tensor([[1.0000, 0.2000, 0.5000],
        [0.2500, 0.5000, 0.1250]])
矩阵乘法:
 tensor([[3., 3.],
        [3., 3.]])
A 的转置: tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
重塑为向量: tensor([1., 1., 1., 1., 1., 1.])
重塑形状: tensor([[1., 1., 1., 1., 1., 1.]])
原始形状: torch.Size([3, 4])
增加维度: torch.Size([1, 3, 4])
减少维度: torch.Size([3, 4])


In [77]:
# L2范数是向量元素平方和的平方根
a = torch.arange(5, dtype=torch.float32)
print('向量a的L2范数\n', torch.norm(a))

向量a的L2范数
 tensor(5.4772)


In [78]:
# L1范数是向量元素的绝对值之和
b = torch.tensor([1.0, -8, 3])
print('向量b的L1范数\n', torch.abs(b).sum())

向量b的L1范数
 tensor(12.)


In [79]:
# F范数是矩阵的弗罗贝尼乌斯范数，是矩阵元素的平方和的平方根
A = torch.arange(12, dtype=torch.float32).reshape(3, 4)
print('矩阵A的F范数：\n', torch.norm(A))

矩阵A的F范数：
 tensor(22.4944)
